// <auto-generated />
namespace SecureTunnelManager.Infrastructure.Security;

internal static partial class ShareFileCrypto
{
    private const string KeyMaterial = "JmS5Hv8X7lzOLKQMPEGDjsB9I46CWYkTrtxUVNenfdFa3yqA";
}
